name: "PR test"
on: pull_request

jobs:
  unit-test-with-asan:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "install dependencies"
        run: sudo ./misc/install-deps.sh -y

      - name: "configure build env"
        run: ./configure

      - name: "build the source"
        run: make ASAN=1

      - name: "run unit tests"
        run: make unittest ASAN=1
